name: Frontend page for profiles

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: octokit/graphql-action@v2.x
      id: get_files
      with:
        query: |
              {
                repository(owner: "ktf", name: "profile-reports") {
                  object(expression: "HEAD:") {
                    ... on Tree {
                      entries {
                        name
                        object {
                          ... on Blob {
                            byteSize
                          }
                        }
                      }
                    }
                  }
                }
              }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update README
      run: |
        cat <<\EOF > README.md
        ## Available profiles
        EOF
        cat <<\EOF | jq '.repository.object.entries[] | select(.name | test(".json")' | jq -r '"- [\(.name)](https://www.speedscope.app/#profileURL=https://raw.githubusercontent.com/ktf/profile-reports/main/\(.name))"' >> README.md
        ${{ steps.get_files.outputs.data }}
        EOF
        cat README.md
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push
